export type TemplateType = "officialForm" | "publicForm" | "genericWorksheet" | "infoOnly" | "flatForm";
export type TemplateSourceKind = "governmentPublic" | "publicForm" | "genericWorksheet" | "sample" | "underReview";

export interface TemplateDirectoryItem {
  file: string;
  slug?: string;
  title: string;
  description: string;
  category: string;
  agency: string;
  pageCount: number;
  estimatedTime: string;
  commonUse: string;
  templateType: TemplateType;
  sourceKind: TemplateSourceKind;
  badge?: string;
  popular?: boolean;
  hideFromMainGrid?: boolean;
  qualityNote?: string;
  allowFill?: boolean;
  indexable?: boolean;
  tags: string[];
}

export const templateDirectory: TemplateDirectoryItem[] = [
  {
    file: "ato-tfn-declaration.pdf",
    slug: "tfn-declaration",
    title: "Tax File Number Declaration",
    description: "Public ATO form (NAT 3092) for declaring your TFN to your employer.",
    category: "ATO",
    agency: "Australian Taxation Office",
    pageCount: 7,
    estimatedTime: "5-8 min",
    commonUse: "starting a new job or changing payroll details",
    templateType: "infoOnly",
    sourceKind: "underReview",
    badge: "Info only",
    hideFromMainGrid: true,
    qualityNote:
      "This TFN Declaration entry is under review because the bundled PDF appears to be an information document rather than a fillable TFN declaration form.",
    allowFill: false,
    indexable: false,
    tags: ["tax", "employment", "new job", "payroll", "NAT 3092", "TFN"],
  },
  {
    file: "ato-super-choice.pdf",
    slug: "super-choice",
    title: "Superannuation Standard Choice",
    description: "Public ATO form (NAT 13080) to choose which super fund receives your contributions.",
    category: "ATO",
    agency: "Australian Taxation Office",
    pageCount: 5,
    estimatedTime: "4-7 min",
    commonUse: "choosing or updating your super fund with an employer",
    templateType: "officialForm",
    sourceKind: "governmentPublic",
    badge: "Official form",
    popular: true,
    tags: ["super", "employment", "new job", "ATO", "NAT 13080"],
  },
  {
    file: "ato-withholding-declaration.pdf",
    title: "Withholding Declaration",
    description: "Public ATO form (NAT 3093) for tax withholding changes, HELP debt, Medicare levy and offsets.",
    category: "ATO",
    agency: "Australian Taxation Office",
    pageCount: 7,
    estimatedTime: "5-8 min",
    commonUse: "updating tax withholding after your circumstances change",
    templateType: "officialForm",
    sourceKind: "governmentPublic",
    badge: "Official form",
    tags: ["tax", "withholding", "HELP debt", "Medicare levy", "NAT 3093"],
  },
  {
    file: "employment-separation.pdf",
    slug: "employment-separation",
    title: "Employment Separation Certificate",
    description: "Public Services Australia form for when employment ends and income support may be needed.",
    category: "Centrelink",
    agency: "Services Australia",
    pageCount: 4,
    estimatedTime: "6-10 min",
    commonUse: "confirming employment details after leaving a job",
    templateType: "officialForm",
    sourceKind: "governmentPublic",
    badge: "Official form",
    popular: true,
    tags: ["Centrelink", "employment", "separation", "income support", "SU001"],
  },
  {
    file: "medicare-enrolment.pdf",
    slug: "medicare-enrolment",
    title: "Medicare Enrolment",
    description: "Public Services Australia form (MS004) for Medicare card applications and enrolment changes.",
    category: "Healthcare",
    agency: "Services Australia",
    pageCount: 17,
    estimatedTime: "10-15 min",
    commonUse: "applying for or updating Medicare enrolment",
    templateType: "officialForm",
    sourceKind: "governmentPublic",
    badge: "Official form",
    tags: ["Medicare", "health", "Services Australia", "MS004", "enrolment"],
  },
  {
    file: "statutory-declaration.pdf",
    slug: "statutory-declaration",
    title: "Statutory Declaration",
    description: "General Australian statutory declaration form with witness section and declaration wording.",
    category: "Legal",
    agency: "Australian public form",
    pageCount: 2,
    estimatedTime: "3-5 min",
    commonUse: "making a formal written declaration",
    templateType: "publicForm",
    sourceKind: "publicForm",
    badge: "Public form",
    popular: true,
    tags: ["legal", "declaration", "witness", "stat dec", "statutory declaration"],
  },
  {
    file: "centrelink-su415.pdf",
    slug: "centrelink-su415",
    title: "Centrelink Income and Assets Form SU415",
    description: "Services Australia form for declaring income, assets, partner details and financial changes.",
    category: "Centrelink",
    agency: "Services Australia",
    pageCount: 2,
    estimatedTime: "8-12 min",
    commonUse: "declaring income and assets to Centrelink",
    templateType: "infoOnly",
    sourceKind: "underReview",
    badge: "Under review",
    hideFromMainGrid: true,
    qualityNote:
      "This Centrelink SU415 entry is under review because the bundled PDF appears incorrect or mislabelled and should not be treated as a valid official form.",
    allowFill: false,
    indexable: false,
    tags: ["Centrelink", "income", "assets", "Services Australia", "SU415"],
  },
  {
    file: "tenancy-application-nsw.pdf",
    slug: "rental-application-nsw",
    title: "Rental Application Worksheet (NSW)",
    description: "Generic New South Wales rental application worksheet with applicant, employment and rental history fields.",
    category: "Real Estate",
    agency: "Generic Australian worksheet",
    pageCount: 3,
    estimatedTime: "7-10 min",
    commonUse: "applying for a rental property in New South Wales",
    templateType: "genericWorksheet",
    sourceKind: "genericWorksheet",
    badge: "Generic worksheet",
    tags: ["rental", "tenancy", "NSW", "worksheet", "real estate"],
  },
  {
    file: "tenancy-application-vic.pdf",
    slug: "rental-application-vic",
    title: "Rental Application Worksheet (VIC)",
    description: "Victoria rental application worksheet under review for currency and prescribed-form accuracy.",
    category: "Real Estate",
    agency: "Generic Australian worksheet",
    pageCount: 3,
    estimatedTime: "7-10 min",
    commonUse: "applying for a rental property in Victoria",
    templateType: "genericWorksheet",
    sourceKind: "underReview",
    badge: "Under review",
    hideFromMainGrid: true,
    qualityNote:
      "This Victorian rental application is under review because it may be outdated or may not match the current prescribed rental application requirements.",
    allowFill: false,
    indexable: false,
    tags: ["rental", "tenancy", "VIC", "worksheet", "real estate"],
  },
  {
    file: "rental-application.pdf",
    title: "Rental Application Worksheet",
    description: "Generic residential rental application worksheet for Australian properties and applicant screening.",
    category: "Real Estate",
    agency: "Generic Australian worksheet",
    pageCount: 2,
    estimatedTime: "6-9 min",
    commonUse: "applying for a rental property with basic details",
    templateType: "genericWorksheet",
    sourceKind: "genericWorksheet",
    badge: "Generic worksheet",
    popular: true,
    tags: ["rental", "tenancy", "lease", "property", "worksheet", "real estate"],
  },
  {
    file: "superannuation-hardship.pdf",
    slug: "super-hardship",
    title: "Superannuation Hardship Release",
    description: "Form for early release of superannuation on financial hardship or compassionate grounds.",
    category: "Superannuation",
    agency: "Australian template",
    pageCount: 2,
    estimatedTime: "8-12 min",
    commonUse: "applying for early access to super in hardship circumstances",
    templateType: "genericWorksheet",
    sourceKind: "genericWorksheet",
    badge: "Generic worksheet",
    tags: ["super", "hardship", "financial hardship", "early release", "fund"],
  },
  {
    file: "employee-details.pdf",
    slug: "employee-details",
    title: "New Employee Details Form",
    description: "Collect TFN, bank details, super fund and emergency contact details from new staff.",
    category: "Employment",
    agency: "Australian workplace template",
    pageCount: 2,
    estimatedTime: "5-8 min",
    commonUse: "onboarding a new employee for payroll setup",
    templateType: "genericWorksheet",
    sourceKind: "genericWorksheet",
    badge: "Generic worksheet",
    popular: true,
    tags: ["employment", "new employee", "payroll", "bank details", "super"],
  },
  {
    file: "australian-invoice.pdf",
    slug: "tax-invoice",
    title: "Tax Invoice",
    description: "Australian tax invoice template with ABN, GST breakdown, line items and payment details.",
    category: "Business",
    agency: "Australian business template",
    pageCount: 2,
    estimatedTime: "3-6 min",
    commonUse: "sending a professional invoice to a customer",
    templateType: "genericWorksheet",
    sourceKind: "sample",
    badge: "Under review",
    hideFromMainGrid: true,
    qualityNote:
      "This tax invoice template is hidden while it is under review because the bundled PDF contains sample data and should be replaced before normal use.",
    allowFill: false,
    indexable: false,
    tags: ["invoice", "tax invoice", "business", "ABN", "GST"],
  },
  {
    file: "consent-form.pdf",
    title: "General Consent Form",
    description: "Simple consent and authority form suitable for community, business and personal use.",
    category: "General",
    agency: "Australian template",
    pageCount: 2,
    estimatedTime: "3-5 min",
    commonUse: "recording signed consent or permission",
    templateType: "genericWorksheet",
    sourceKind: "genericWorksheet",
    badge: "Generic worksheet",
    tags: ["consent", "permission", "authority", "signature", "general"],
  },
  {
    file: "medical-consent.pdf",
    slug: "medical-consent",
    title: "Medical Consent Form",
    description: "Patient consent form with Medicare number, allergies, emergency contact and signatures.",
    category: "Healthcare",
    agency: "Australian healthcare template",
    pageCount: 2,
    estimatedTime: "5-8 min",
    commonUse: "recording patient consent before treatment or procedures",
    templateType: "genericWorksheet",
    sourceKind: "genericWorksheet",
    badge: "Generic worksheet",
    tags: ["medical", "health", "consent", "patient", "Medicare"],
  },
  {
    file: "bank-account-change.pdf",
    title: "Bank Account Update Request",
    description: "Update bank account details with an employer, super fund or organisation.",
    category: "Finance",
    agency: "Australian finance template",
    pageCount: 2,
    estimatedTime: "3-5 min",
    commonUse: "changing payment details with an organisation",
    templateType: "genericWorksheet",
    sourceKind: "genericWorksheet",
    badge: "Generic worksheet",
    tags: ["bank", "payment", "finance", "account", "payroll"],
  },
  {
    file: "insurance-claim.pdf",
    title: "Insurance Claim Form",
    description: "General insurance claim form for home, motor and personal property claims.",
    category: "Insurance",
    agency: "Australian insurance template",
    pageCount: 2,
    estimatedTime: "8-12 min",
    commonUse: "lodging an insurance claim with supporting details",
    templateType: "genericWorksheet",
    sourceKind: "genericWorksheet",
    badge: "Generic worksheet",
    tags: ["insurance", "claim", "home", "motor", "property"],
  },
  {
    file: "ndis-service-agreement.pdf",
    slug: "ndis-service-agreement",
    title: "NDIS Service Agreement",
    description: "Service agreement between an NDIS participant and provider with supports, rates and signatures.",
    category: "NDIS",
    agency: "NDIS provider template",
    pageCount: 2,
    estimatedTime: "8-12 min",
    commonUse: "confirming supports between a participant and provider",
    templateType: "genericWorksheet",
    sourceKind: "genericWorksheet",
    badge: "Generic worksheet",
    tags: ["NDIS", "service agreement", "disability", "provider", "participant"],
  },
];

export const visibleTemplateDirectory = templateDirectory.filter((template) => !template.hideFromMainGrid);

export const templateCount = visibleTemplateDirectory.length;
